version: 0.2

phases:
  pre_build:
    commands:
      - echo "Starting PayLater CodeBuild..."
      - echo "Checking Docker..."
      - docker --version
      - echo "Logging in to Amazon ECR..."
      - export AWS_ACCOUNT_ID=330468768104
      - export AWS_DEFAULT_REGION=eu-north-1
      - export ECR_URI=${AWS_ACCOUNT_ID}.dkr.ecr.${AWS_DEFAULT_REGION}.amazonaws.com
      - export IMAGE_TAG=build-${CODEBUILD_BUILD_NUMBER}
      - aws ecr get-login-password --region ${AWS_DEFAULT_REGION} | docker login --username AWS --password-stdin ${ECR_URI}

  build:
    commands:
      - echo "Building PayLater Docker images..."

      - docker build -t paylater-api-gateway .

      - docker build -t paylater-frontend ./paylater-frontend

      - docker build -t paylater-identity-service -f identity-service/Dockerfile .

      - docker build -t paylater-customer-service -f customer-service/Dockerfile .

      - docker build -t paylater-merchant-service -f merchant-service/Dockerfile .

      - docker build -t paylater-transaction-service -f transaction-service/Dockerfile .

      - docker build -t paylater-payback-service -f payback-service/Dockerfile .

      - docker build -t paylater-reporting-service -f reporting-service/Dockerfile .

      - echo "Tagging images for ECR..."

      - docker tag paylater-api-gateway:latest ${ECR_URI}/paylater-api-gateway:${IMAGE_TAG}
      - docker tag paylater-frontend:latest ${ECR_URI}/paylater-frontend:${IMAGE_TAG}
      - docker tag paylater-identity-service:latest ${ECR_URI}/paylater-identity-service:${IMAGE_TAG}
      - docker tag paylater-customer-service:latest ${ECR_URI}/paylater-customer-service:${IMAGE_TAG}
      - docker tag paylater-merchant-service:latest ${ECR_URI}/paylater-merchant-service:${IMAGE_TAG}
      - docker tag paylater-transaction-service:latest ${ECR_URI}/paylater-transaction-service:${IMAGE_TAG}
      - docker tag paylater-payback-service:latest ${ECR_URI}/paylater-payback-service:${IMAGE_TAG}
      - docker tag paylater-reporting-service:latest ${ECR_URI}/paylater-reporting-service:${IMAGE_TAG}

  post_build:
    commands:
      - echo "Pushing PayLater images to ECR..."

      - docker push ${ECR_URI}/paylater-api-gateway:${IMAGE_TAG}
      - docker push ${ECR_URI}/paylater-frontend:${IMAGE_TAG}
      - docker push ${ECR_URI}/paylater-identity-service:${IMAGE_TAG}
      - docker push ${ECR_URI}/paylater-customer-service:${IMAGE_TAG}
      - docker push ${ECR_URI}/paylater-merchant-service:${IMAGE_TAG}
      - docker push ${ECR_URI}/paylater-transaction-service:${IMAGE_TAG}
      - docker push ${ECR_URI}/paylater-payback-service:${IMAGE_TAG}
      - docker push ${ECR_URI}/paylater-reporting-service:${IMAGE_TAG}

      - echo "All PayLater images pushed to ECR successfully."
