// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1
// source: merchant.sql

package sqlc

import (
	"context"
	"database/sql"
	"time"
)

const createMerchant = `-- name: CreateMerchant :execresult
INSERT INTO merchants (
    merchant_name,
    phone_number,
    onboarding,
    commission
) VALUES (?, ?, ?, ?)
`

type CreateMerchantParams struct {
	MerchantName string
	PhoneNumber  string
	Onboarding   time.Time
	Commission   string
}

func (q *Queries) CreateMerchant(ctx context.Context, arg CreateMerchantParams) (sql.Result, error) {
	return q.db.ExecContext(ctx, createMerchant,
		arg.MerchantName,
		arg.PhoneNumber,
		arg.Onboarding,
		arg.Commission,
	)
}

const deleteMerchant = `-- name: DeleteMerchant :exec
DELETE FROM merchants
WHERE id = ?
`

func (q *Queries) DeleteMerchant(ctx context.Context, id int64) error {
	_, err := q.db.ExecContext(ctx, deleteMerchant, id)
	return err
}

const getMerchant = `-- name: GetMerchant :one
SELECT id, merchant_name, phone_number, onboarding, commission
FROM merchants
WHERE id = ?
`

func (q *Queries) GetMerchant(ctx context.Context, id int64) (Merchant, error) {
	row := q.db.QueryRowContext(ctx, getMerchant, id)
	var i Merchant
	err := row.Scan(
		&i.ID,
		&i.MerchantName,
		&i.PhoneNumber,
		&i.Onboarding,
		&i.Commission,
	)
	return i, err
}

const listMerchants = `-- name: ListMerchants :many
SELECT id, merchant_name, phone_number, onboarding, commission
FROM merchants
`

func (q *Queries) ListMerchants(ctx context.Context) ([]Merchant, error) {
	rows, err := q.db.QueryContext(ctx, listMerchants)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []Merchant
	for rows.Next() {
		var i Merchant
		if err := rows.Scan(
			&i.ID,
			&i.MerchantName,
			&i.PhoneNumber,
			&i.Onboarding,
			&i.Commission,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const updateMerchant = `-- name: UpdateMerchant :exec
UPDATE merchants
SET
    merchant_name = ?,
    phone_number = ?,
    onboarding = ?,
    commission = ?
WHERE id = ?
`

type UpdateMerchantParams struct {
	MerchantName string
	PhoneNumber  string
	Onboarding   time.Time
	Commission   string
	ID           int64
}

func (q *Queries) UpdateMerchant(ctx context.Context, arg UpdateMerchantParams) error {
	_, err := q.db.ExecContext(ctx, updateMerchant,
		arg.MerchantName,
		arg.PhoneNumber,
		arg.Onboarding,
		arg.Commission,
		arg.ID,
	)
	return err
}
