// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1
// source: merchant.sql

package sqlc

import (
	"context"
	"database/sql"
	"time"
)

const createMerchant = `-- name: CreateMerchant :execresult



INSERT INTO merchants (
    merchant_name,
    phone_number,
    onboarding,
    commission
)
VALUES (?, ?, ?, ?)
`

type CreateMerchantParams struct {
	MerchantName string
	PhoneNumber  string
	Onboarding   time.Time
	Commission   string
}

// ===========================
// Merchant Queries
// ===========================
// ===========================
// Create Merchant
// ===========================
// Creates/onboards a new merchant.
//
// SQLC generates:
// CreateMerchant(ctx, params)
func (q *Queries) CreateMerchant(ctx context.Context, arg CreateMerchantParams) (sql.Result, error) {
	return q.db.ExecContext(ctx, createMerchant,
		arg.MerchantName,
		arg.PhoneNumber,
		arg.Onboarding,
		arg.Commission,
	)
}

const updateMerchantCommission = `-- name: UpdateMerchantCommission :exec

UPDATE merchants
SET commission = ?
WHERE id = ?
`

type UpdateMerchantCommissionParams struct {
	Commission string
	ID         int64
}

// ===========================
// Update Merchant Commission
// ===========================
// Updates only the commission percentage
// for an existing merchant.
//
// Merchant is identified using its ID.
//
// SQLC generates:
// UpdateMerchantCommission(ctx, params)
func (q *Queries) UpdateMerchantCommission(ctx context.Context, arg UpdateMerchantCommissionParams) error {
	_, err := q.db.ExecContext(ctx, updateMerchantCommission, arg.Commission, arg.ID)
	return err
}
