// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1
// source: payback.sql

package sqlc

import (
	"context"
	"database/sql"
	"time"
)

const createPayback = `-- name: CreatePayback :execresult
INSERT INTO paybacks (
    customer_id,
    amount,
    payment_date
) VALUES (?, ?, ?)
`

type CreatePaybackParams struct {
	CustomerID  int64
	Amount      string
	PaymentDate time.Time
}

func (q *Queries) CreatePayback(ctx context.Context, arg CreatePaybackParams) (sql.Result, error) {
	return q.db.ExecContext(ctx, createPayback, arg.CustomerID, arg.Amount, arg.PaymentDate)
}

const deletePayback = `-- name: DeletePayback :exec
DELETE FROM paybacks
WHERE id = ?
`

func (q *Queries) DeletePayback(ctx context.Context, id int64) error {
	_, err := q.db.ExecContext(ctx, deletePayback, id)
	return err
}

const getPayback = `-- name: GetPayback :one
SELECT id, customer_id, amount, payment_date
FROM paybacks
WHERE id = ?
`

func (q *Queries) GetPayback(ctx context.Context, id int64) (Payback, error) {
	row := q.db.QueryRowContext(ctx, getPayback, id)
	var i Payback
	err := row.Scan(
		&i.ID,
		&i.CustomerID,
		&i.Amount,
		&i.PaymentDate,
	)
	return i, err
}

const listPaybacks = `-- name: ListPaybacks :many
SELECT id, customer_id, amount, payment_date
FROM paybacks
`

func (q *Queries) ListPaybacks(ctx context.Context) ([]Payback, error) {
	rows, err := q.db.QueryContext(ctx, listPaybacks)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []Payback
	for rows.Next() {
		var i Payback
		if err := rows.Scan(
			&i.ID,
			&i.CustomerID,
			&i.Amount,
			&i.PaymentDate,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}
