// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1
// source: transaction.sql

package sqlc

import (
	"context"
	"database/sql"
	"time"
)

const createTransaction = `-- name: CreateTransaction :execresult



INSERT INTO transactions (
    customer_id,
    merchant_id,
    amount,
    commission,
    transaction_date
)
VALUES (?, ?, ?, ?, ?)
`

type CreateTransactionParams struct {
	CustomerID      int64
	MerchantID      int64
	Amount          string
	Commission      string
	TransactionDate time.Time
}

// ===========================
// Transaction Queries
// ===========================
// Contains SQL queries related to PayLater transactions.
// ===========================
// Create Transaction
// ===========================
// Creates a new PayLater transaction when a customer
// purchases something from a merchant.
//
// Stores:
// customer_id      -> Customer making the purchase
// merchant_id      -> Merchant where purchase happened
// amount           -> Purchase amount
// commission       -> Merchant commission for transaction
// transaction_date -> Date of purchase
//
// SQLC generates:
// CreateTransaction(ctx, params)
func (q *Queries) CreateTransaction(ctx context.Context, arg CreateTransactionParams) (sql.Result, error) {
	return q.db.ExecContext(ctx, createTransaction,
		arg.CustomerID,
		arg.MerchantID,
		arg.Amount,
		arg.Commission,
		arg.TransactionDate,
	)
}
