// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1
// source: transaction.sql

package sqlc

import (
	"context"
	"database/sql"
	"time"
)

const createTransaction = `-- name: CreateTransaction :execresult
INSERT INTO transactions (
    customer_id,
    merchant_id,
    amount,
    commission,
    transaction_date
) VALUES (?, ?, ?, ?, ?)
`

type CreateTransactionParams struct {
	CustomerID      int64
	MerchantID      int64
	Amount          string
	Commission      string
	TransactionDate time.Time
}

func (q *Queries) CreateTransaction(ctx context.Context, arg CreateTransactionParams) (sql.Result, error) {
	return q.db.ExecContext(ctx, createTransaction,
		arg.CustomerID,
		arg.MerchantID,
		arg.Amount,
		arg.Commission,
		arg.TransactionDate,
	)
}

const deleteTransaction = `-- name: DeleteTransaction :exec
DELETE FROM transactions
WHERE id = ?
`

func (q *Queries) DeleteTransaction(ctx context.Context, id int64) error {
	_, err := q.db.ExecContext(ctx, deleteTransaction, id)
	return err
}

const getTransaction = `-- name: GetTransaction :one
SELECT id, customer_id, merchant_id, amount, commission, transaction_date
FROM transactions
WHERE id = ?
`

func (q *Queries) GetTransaction(ctx context.Context, id int64) (Transaction, error) {
	row := q.db.QueryRowContext(ctx, getTransaction, id)
	var i Transaction
	err := row.Scan(
		&i.ID,
		&i.CustomerID,
		&i.MerchantID,
		&i.Amount,
		&i.Commission,
		&i.TransactionDate,
	)
	return i, err
}

const listTransactions = `-- name: ListTransactions :many
SELECT id, customer_id, merchant_id, amount, commission, transaction_date
FROM transactions
`

func (q *Queries) ListTransactions(ctx context.Context) ([]Transaction, error) {
	rows, err := q.db.QueryContext(ctx, listTransactions)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []Transaction
	for rows.Next() {
		var i Transaction
		if err := rows.Scan(
			&i.ID,
			&i.CustomerID,
			&i.MerchantID,
			&i.Amount,
			&i.Commission,
			&i.TransactionDate,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const updateTransaction = `-- name: UpdateTransaction :exec
UPDATE transactions
SET
    customer_id = ?,
    merchant_id = ?,
    amount = ?,
    commission = ?,
    transaction_date = ?
WHERE id = ?
`

type UpdateTransactionParams struct {
	CustomerID      int64
	MerchantID      int64
	Amount          string
	Commission      string
	TransactionDate time.Time
	ID              int64
}

func (q *Queries) UpdateTransaction(ctx context.Context, arg UpdateTransactionParams) error {
	_, err := q.db.ExecContext(ctx, updateTransaction,
		arg.CustomerID,
		arg.MerchantID,
		arg.Amount,
		arg.Commission,
		arg.TransactionDate,
		arg.ID,
	)
	return err
}
