// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1
// source: merchant.sql

package sqlc

import (
	"context"
	"database/sql"
	"time"
)

const createMerchant = `-- name: CreateMerchant :execresult



INSERT INTO merchants (
    merchant_name,
    phone_number,
    onboarding,
    commission
)
VALUES (?, ?, ?, ?)
`

type CreateMerchantParams struct {
	MerchantName string
	PhoneNumber  string
	Onboarding   time.Time
	Commission   string
}

// ===========================
// Merchant Queries
// ===========================
// SQLC inputs for Merchant Service (merchant_db).
// CreateMerchant onboards a merchant; UpdateMerchantCommission
// changes fee percent used by reporting. Generated code: db/sqlc.
// ===========================
// Create Merchant
// ===========================
// Creates/onboards a new merchant.
//
// SQLC generates:
// CreateMerchant(ctx, params)
func (q *Queries) CreateMerchant(ctx context.Context, arg CreateMerchantParams) (sql.Result, error) {
	return q.db.ExecContext(ctx, createMerchant,
		arg.MerchantName,
		arg.PhoneNumber,
		arg.Onboarding,
		arg.Commission,
	)
}

const updateMerchantCommission = `-- name: UpdateMerchantCommission :execrows

UPDATE merchants
SET commission = ?
WHERE id = ?
`

type UpdateMerchantCommissionParams struct {
	Commission string
	ID         int64
}

// ===========================
// Update Merchant Commission
// ===========================
// Updates only the commission percentage
// for an existing merchant.
//
// Merchant is identified using its ID.
//
// SQLC generates:
// UpdateMerchantCommission(ctx, params)
func (q *Queries) UpdateMerchantCommission(ctx context.Context, arg UpdateMerchantCommissionParams) (int64, error) {
	result, err := q.db.ExecContext(ctx, updateMerchantCommission, arg.Commission, arg.ID)
	if err != nil {
		return 0, err
	}
	return result.RowsAffected()
}
