// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1
// source: merchant.sql

package sqlc

import (
	"context"
	"database/sql"
	"time"
)

const createMerchant = `-- name: CreateMerchant :execresult

INSERT INTO merchants (
    merchant_name,
    phone_number,
    onboarding,
    commission,
    user_id
)
VALUES (?, ?, ?, ?, ?)
`

type CreateMerchantParams struct {
	MerchantName string
	PhoneNumber  string
	Onboarding   time.Time
	Commission   string
	UserID       sql.NullInt64
}

// ===========================
// Merchant Queries
// ===========================
func (q *Queries) CreateMerchant(ctx context.Context, arg CreateMerchantParams) (sql.Result, error) {
	return q.db.ExecContext(ctx, createMerchant,
		arg.MerchantName,
		arg.PhoneNumber,
		arg.Onboarding,
		arg.Commission,
		arg.UserID,
	)
}

const getMerchantByID = `-- name: GetMerchantByID :one
SELECT
    id,
    merchant_name,
    phone_number,
    onboarding,
    commission,
    user_id
FROM merchants
WHERE id = ?
LIMIT 1
`

func (q *Queries) GetMerchantByID(ctx context.Context, id int64) (Merchant, error) {
	row := q.db.QueryRowContext(ctx, getMerchantByID, id)
	var i Merchant
	err := row.Scan(
		&i.ID,
		&i.MerchantName,
		&i.PhoneNumber,
		&i.Onboarding,
		&i.Commission,
		&i.UserID,
	)
	return i, err
}

const getMerchantByUserID = `-- name: GetMerchantByUserID :one
SELECT
    id,
    merchant_name,
    phone_number,
    onboarding,
    commission,
    user_id
FROM merchants
WHERE user_id = ?
LIMIT 1
`

func (q *Queries) GetMerchantByUserID(ctx context.Context, userID sql.NullInt64) (Merchant, error) {
	row := q.db.QueryRowContext(ctx, getMerchantByUserID, userID)
	var i Merchant
	err := row.Scan(
		&i.ID,
		&i.MerchantName,
		&i.PhoneNumber,
		&i.Onboarding,
		&i.Commission,
		&i.UserID,
	)
	return i, err
}

const updateMerchantCommission = `-- name: UpdateMerchantCommission :execrows
UPDATE merchants
SET commission = ?
WHERE id = ?
`

type UpdateMerchantCommissionParams struct {
	Commission string
	ID         int64
}

func (q *Queries) UpdateMerchantCommission(ctx context.Context, arg UpdateMerchantCommissionParams) (int64, error) {
	result, err := q.db.ExecContext(ctx, updateMerchantCommission, arg.Commission, arg.ID)
	if err != nil {
		return 0, err
	}
	return result.RowsAffected()
}
