// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1

package sqlc

import (
	"database/sql"
	"time"
)

type Merchant struct {
	ID           int64
	MerchantName string
	PhoneNumber  string
	Onboarding   time.Time
	Commission   string
	UserID       sql.NullInt64
}
