package handlers

import (
	"net/http"
	"strconv"
	"time"

	"github.com/gin-gonic/gin"

	"paylater/db/sqlc"
	"paylater/services"
)

// ==========================================================
// Request Structures
// ==========================================================

// CreateMerchantRequest represents the JSON body
// received when creating/onboarding a new merchant.
type CreateMerchantRequest struct {
	MerchantName string `json:"merchant_name" binding:"required"`
	PhoneNumber  string `json:"phone_number" binding:"required"`
	Onboarding   string `json:"onboarding" binding:"required"`
	Commission   string `json:"commission" binding:"required"`
}

// UpdateMerchantCommissionRequest represents the JSON body
// received when updating a merchant's commission.
//
// We only update commission, so merchant name,
// phone number and onboarding date are not required.
type UpdateMerchantCommissionRequest struct {
	Commission string `json:"commission" binding:"required"`
}

// ==========================================================
// Merchant Handler
// ==========================================================

// MerchantHandler handles merchant-related HTTP requests.
type MerchantHandler struct {
	service *services.MerchantService
}

// NewMerchantHandler creates a new MerchantHandler.
func NewMerchantHandler(
	service *services.MerchantService,
) *MerchantHandler {

	return &MerchantHandler{
		service: service,
	}
}

// ==========================================================
// POST /merchants
// ==========================================================

// CreateMerchant creates/onboards a new merchant.
func (h *MerchantHandler) CreateMerchant(c *gin.Context) {

	// Store the incoming JSON request.
	var req CreateMerchantRequest

	// Read and validate the JSON body.
	if err := c.ShouldBindJSON(&req); err != nil {
		c.JSON(http.StatusBadRequest, gin.H{
			"error": err.Error(),
		})
		return
	}

	// The API receives onboarding as a string:
	//
	// "2026-07-29"
	//
	// SQLC expects time.Time because the MySQL
	// onboarding column uses the DATE datatype.
	onboardingDate, err := time.Parse(
		"2006-01-02",
		req.Onboarding,
	)

	if err != nil {
		c.JSON(http.StatusBadRequest, gin.H{
			"error": "onboarding must be in YYYY-MM-DD format",
		})
		return
	}

	// Convert the API request into the parameters
	// generated by SQLC.
	params := sqlc.CreateMerchantParams{
		MerchantName: req.MerchantName,
		PhoneNumber:  req.PhoneNumber,
		Onboarding:   onboardingDate,
		Commission:   req.Commission,
	}

	// Send the merchant information to the service layer.
	err = h.service.CreateMerchant(
		c.Request.Context(),
		params,
	)

	if err != nil {
		c.JSON(http.StatusInternalServerError, gin.H{
			"error": err.Error(),
		})
		return
	}

	// Merchant created successfully.
	c.JSON(http.StatusCreated, gin.H{
		"message": "Merchant created successfully",
	})
}

// ==========================================================
// PUT /merchants/:id
// ==========================================================

// UpdateMerchantCommission updates the commission
// percentage of an existing merchant.
//
// Example:
//
// PUT /merchants/1
//
// {
//     "commission": "7.00"
// }
func (h *MerchantHandler) UpdateMerchantCommission(c *gin.Context) {

	// ------------------------------------------------------
	// Get Merchant ID from URL
	// ------------------------------------------------------

	// c.Param("id") returns the ID as a string.
	//
	// Example:
	// /merchants/1
	//
	// id = "1"
	id, err := strconv.ParseInt(
		c.Param("id"),
		10,
		64,
	)

	if err != nil {
		c.JSON(http.StatusBadRequest, gin.H{
			"error": "Invalid merchant ID",
		})
		return
	}

	// ------------------------------------------------------
	// Read Request Body
	// ------------------------------------------------------

	var req UpdateMerchantCommissionRequest

	if err := c.ShouldBindJSON(&req); err != nil {
		c.JSON(http.StatusBadRequest, gin.H{
			"error": err.Error(),
		})
		return
	}

	// ------------------------------------------------------
	// Prepare SQLC Parameters
	// ------------------------------------------------------

	params := sqlc.UpdateMerchantCommissionParams{
		Commission: req.Commission,
		ID:         id,
	}

	// ------------------------------------------------------
	// Call Service
	// ------------------------------------------------------

	err = h.service.UpdateMerchantCommission(
		c.Request.Context(),
		params,
	)

	if err != nil {
		c.JSON(http.StatusInternalServerError, gin.H{
			"error": err.Error(),
		})
		return
	}

	// ------------------------------------------------------
	// Success Response
	// ------------------------------------------------------

	c.JSON(http.StatusOK, gin.H{
		"message": "Merchant commission updated successfully",
	})
}