// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1

package sqlc

import (
	"time"
)

type Transaction struct {
	ID              int64
	CustomerID      int64
	MerchantID      int64
	Amount          string
	Commission      string
	TransactionDate time.Time
}
