// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1
// source: transaction.sql

package sqlc

import (
	"context"
	"database/sql"
	"time"
)

const createTransaction = `-- name: CreateTransaction :execresult



INSERT INTO transactions (
    customer_id,
    merchant_id,
    amount,
    commission,
    transaction_date
)
VALUES (?, ?, ?, ?, ?)
`

type CreateTransactionParams struct {
	CustomerID      int64
	MerchantID      int64
	Amount          string
	Commission      string
	TransactionDate time.Time
}

// ===========================
// Transaction Queries
// ===========================
// Contains SQL queries related to PayLater transactions.
// ===========================
// Create Transaction
// ===========================
// Creates a new PayLater transaction when a customer
// purchases something from a merchant.
//
// Stores:
// customer_id      -> Customer making the purchase
// merchant_id      -> Merchant where purchase happened
// amount           -> Purchase amount
// commission       -> Merchant commission for transaction
// transaction_date -> Date of purchase
//
// SQLC generates:
// CreateTransaction(ctx, params)
func (q *Queries) CreateTransaction(ctx context.Context, arg CreateTransactionParams) (sql.Result, error) {
	return q.db.ExecContext(ctx, createTransaction,
		arg.CustomerID,
		arg.MerchantID,
		arg.Amount,
		arg.Commission,
		arg.TransactionDate,
	)
}

const listTransactions = `-- name: ListTransactions :many

SELECT
    id,
    customer_id,
    merchant_id,
    amount,
    commission,
    transaction_date
FROM transactions
ORDER BY id DESC
`

// ===========================
// List Transactions
// ===========================
// Returns all transactions ordered by newest first.
func (q *Queries) ListTransactions(ctx context.Context) ([]Transaction, error) {
	rows, err := q.db.QueryContext(ctx, listTransactions)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []Transaction
	for rows.Next() {
		var i Transaction
		if err := rows.Scan(
			&i.ID,
			&i.CustomerID,
			&i.MerchantID,
			&i.Amount,
			&i.Commission,
			&i.TransactionDate,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listTransactionsByCustomerID = `-- name: ListTransactionsByCustomerID :many

SELECT
    id,
    customer_id,
    merchant_id,
    amount,
    commission,
    transaction_date
FROM transactions
WHERE customer_id = ?
ORDER BY id DESC
`

// ===========================
// List Transactions By Customer ID
// ===========================
// Returns transactions for a single customer ordered by newest first.
func (q *Queries) ListTransactionsByCustomerID(ctx context.Context, customerID int64) ([]Transaction, error) {
	rows, err := q.db.QueryContext(ctx, listTransactionsByCustomerID, customerID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []Transaction
	for rows.Next() {
		var i Transaction
		if err := rows.Scan(
			&i.ID,
			&i.CustomerID,
			&i.MerchantID,
			&i.Amount,
			&i.Commission,
			&i.TransactionDate,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}
