namespace: paylater-dev

gateway:
  replicas: 3

  image: paylater-api-gateway
  tag: v3

  resources:
    requests:
      cpu: 100m
      memory: 128Mi

    limits:
      cpu: 500m
      memory: 512Mi
