namespace: paylater-dev

gateway:
  replicas: 3

  image: galinkivamshi/paylater-api-gateway
  tag: 2026.09.02-9307833
  imagePullPolicy: IfNotPresent

  resources:
    requests:
      cpu: 100m
      memory: 128Mi

    limits:
      cpu: 500m
      memory: 512Mi
