// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1
// source: customer.sql

package sqlc

import (
	"context"
	"database/sql"
)

const createCustomer = `-- name: CreateCustomer :execresult



INSERT INTO customers (
    name,
    email,
    credit_limit
)
VALUES (?, ?, ?)
`

type CreateCustomerParams struct {
	Name        string
	Email       string
	CreditLimit string
}

// ===========================
// Customer Queries
// ===========================
// Contains SQL queries used by SQLC
// for customer-related database operations.
// ===========================
// Create Customer
// ===========================
// Creates a new customer with:
// name, email and credit limit.
//
// SQLC generates:
// CreateCustomer(ctx, params)
func (q *Queries) CreateCustomer(ctx context.Context, arg CreateCustomerParams) (sql.Result, error) {
	return q.db.ExecContext(ctx, createCustomer, arg.Name, arg.Email, arg.CreditLimit)
}

const listCustomers = `-- name: ListCustomers :many

SELECT
    id,
    name,
    email,
    credit_limit
FROM customers
ORDER BY id ASC
`

// ===========================
// List Customers
// ===========================
// Retrieves all customers from the database.
//
// Customers are returned in ascending order
// based on their ID.
//
// SQLC generates:
// ListCustomers(ctx)
func (q *Queries) ListCustomers(ctx context.Context) ([]Customer, error) {
	rows, err := q.db.QueryContext(ctx, listCustomers)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []Customer
	for rows.Next() {
		var i Customer
		if err := rows.Scan(
			&i.ID,
			&i.Name,
			&i.Email,
			&i.CreditLimit,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}
