// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1
// source: customer.sql

package sqlc

import (
	"context"
	"database/sql"
)

const createCustomer = `-- name: CreateCustomer :execresult



INSERT INTO customers (
    user_id,
    name,
    email,
    credit_limit
)
VALUES (?, ?, ?, ?)
`

type CreateCustomerParams struct {
	UserID      sql.NullInt64
	Name        string
	Email       string
	CreditLimit string
}

// ===========================
// Customer Queries
// ===========================
// Contains SQL queries used by SQLC
// for customer-related database operations.
// ===========================
// Create Customer
// ===========================
// Creates a new customer with:
// name, email, credit limit, and optional identity user_id link.
//
// SQLC generates:
// CreateCustomer(ctx, params)
func (q *Queries) CreateCustomer(ctx context.Context, arg CreateCustomerParams) (sql.Result, error) {
	return q.db.ExecContext(ctx, createCustomer,
		arg.UserID,
		arg.Name,
		arg.Email,
		arg.CreditLimit,
	)
}

const getCustomerIDByUserID = `-- name: GetCustomerIDByUserID :one

SELECT id
FROM customers
WHERE user_id = ?
LIMIT 1
`

// ===========================
// Get Customer ID By User ID
// ===========================
// Resolves the customer profile owned by an identity user.
//
// SQLC generates:
// GetCustomerIDByUserID(ctx, user_id)
func (q *Queries) GetCustomerIDByUserID(ctx context.Context, userID sql.NullInt64) (int64, error) {
	row := q.db.QueryRowContext(ctx, getCustomerIDByUserID, userID)
	var id int64
	err := row.Scan(&id)
	return id, err
}

const listCustomers = `-- name: ListCustomers :many

SELECT
    id,
    user_id,
    name,
    email,
    credit_limit
FROM customers
ORDER BY id ASC
`

// ===========================
// List Customers
// ===========================
// Retrieves all customers from the database.
//
// Customers are returned in ascending order
// based on their ID.
//
// SQLC generates:
// ListCustomers(ctx)
func (q *Queries) ListCustomers(ctx context.Context) ([]Customer, error) {
	rows, err := q.db.QueryContext(ctx, listCustomers)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []Customer
	for rows.Next() {
		var i Customer
		if err := rows.Scan(
			&i.ID,
			&i.UserID,
			&i.Name,
			&i.Email,
			&i.CreditLimit,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}
