// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1

package sqlc

import (
	"time"
)

type Customer struct {
	ID          int64
	Name        string
	Email       string
	CreditLimit string
}

type Merchant struct {
	ID           int64
	MerchantName string
	PhoneNumber  string
	Onboarding   time.Time
	Commission   string
}

type Payback struct {
	ID          int64
	CustomerID  int64
	Amount      string
	PaymentDate time.Time
}

type Transaction struct {
	ID              int64
	CustomerID      int64
	MerchantID      int64
	Amount          string
	Commission      string
	TransactionDate time.Time
}
