// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1

package sqlc

import (
	"time"
)

type Payback struct {
	ID          int64
	CustomerID  int64
	Amount      string
	PaymentDate time.Time
}
