// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1
// source: payback.sql

package sqlc

import (
	"context"
	"database/sql"
	"time"
)

const createPayback = `-- name: CreatePayback :execresult



INSERT INTO paybacks (
    customer_id,
    amount,
    payment_date
)
VALUES (?, ?, ?)
`

type CreatePaybackParams struct {
	CustomerID  int64
	Amount      string
	PaymentDate time.Time
}

// ===========================
// Payback Queries
// ===========================
// Contains SQL queries related to
// customer repayments in the PayLater system.
// ===========================
// Create Payback
// ===========================
// Creates a repayment record when a customer
// pays back an amount they owe.
//
// customer_id  -> Customer making the repayment
// amount       -> Amount customer is paying back
// payment_date -> Date when repayment happened
//
// SQLC generates:
// CreatePayback(ctx, params)
func (q *Queries) CreatePayback(ctx context.Context, arg CreatePaybackParams) (sql.Result, error) {
	return q.db.ExecContext(ctx, createPayback, arg.CustomerID, arg.Amount, arg.PaymentDate)
}

const listPaybacks = `-- name: ListPaybacks :many

SELECT
    id,
    customer_id,
    amount,
    payment_date
FROM paybacks
ORDER BY id DESC
`

// ===========================
// List Paybacks
// ===========================
// Returns all paybacks ordered by newest first.
func (q *Queries) ListPaybacks(ctx context.Context) ([]Payback, error) {
	rows, err := q.db.QueryContext(ctx, listPaybacks)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []Payback
	for rows.Next() {
		var i Payback
		if err := rows.Scan(
			&i.ID,
			&i.CustomerID,
			&i.Amount,
			&i.PaymentDate,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listPaybacksByCustomerID = `-- name: ListPaybacksByCustomerID :many

SELECT
    id,
    customer_id,
    amount,
    payment_date
FROM paybacks
WHERE customer_id = ?
ORDER BY id DESC
`

// ===========================
// List Paybacks By Customer ID
// ===========================
// Returns paybacks for a single customer ordered by newest first.
func (q *Queries) ListPaybacksByCustomerID(ctx context.Context, customerID int64) ([]Payback, error) {
	rows, err := q.db.QueryContext(ctx, listPaybacksByCustomerID, customerID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []Payback
	for rows.Next() {
		var i Payback
		if err := rows.Scan(
			&i.ID,
			&i.CustomerID,
			&i.Amount,
			&i.PaymentDate,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}
