// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1
// source: payback.sql

package sqlc

import (
	"context"
	"database/sql"
	"time"
)

const createPayback = `-- name: CreatePayback :execresult



INSERT INTO paybacks (
    customer_id,
    amount,
    payment_date
)
VALUES (?, ?, ?)
`

type CreatePaybackParams struct {
	CustomerID  int64
	Amount      string
	PaymentDate time.Time
}

// ===========================
// Payback Queries
// ===========================
// Contains SQL queries related to
// customer repayments in the PayLater system.
// ===========================
// Create Payback
// ===========================
// Creates a repayment record when a customer
// pays back an amount they owe.
//
// customer_id  -> Customer making the repayment
// amount       -> Amount customer is paying back
// payment_date -> Date when repayment happened
//
// SQLC generates:
// CreatePayback(ctx, params)
func (q *Queries) CreatePayback(ctx context.Context, arg CreatePaybackParams) (sql.Result, error) {
	return q.db.ExecContext(ctx, createPayback, arg.CustomerID, arg.Amount, arg.PaymentDate)
}
